- name: Crear servicio para Jenkins
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: jenkins
        namespace: default
      spec:
        type: LoadBalancer
        selector:
          app: jenkins
        ports:
          - port: 80
