- name: Crear almacenamiento persistente en AKS
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        namespace: default
        name: jenkins-pvc    
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

