- name: Crear secretos en AKS
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: secret-pass
        namespace: default
      type: Opaque
      data:
        JENKINS_ADMIN_PASSWORD: bXlzcWwxMjM0
